---
title: "Introduction_RhodopXin"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction_RhodopXin}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(RhodopXin)
```

## Introduction

`Rhodopxin` is an R package designed for the exploratory analysis of rhodopsins by looking at their  sequence and structural characteristics

To download **RhodopXin**, use the following commands:

``` r
require("devtools")
devtools::install_github("calicac001/RhodopXin", build_vignettes = TRUE)
library("RhodopXin")
```

To list all sample functions available in the package:
``` r
ls("package:RhodopXin")
```

<!-- To list all sample datasets available in the package: -->
<!-- ``` r -->
<!-- data(package = "RhodopXin") -->
<!-- ``` -->

## Applications

### Explore Structure of Rhodopsin
```{r, warning=FALSE}
temp_path <- system.file("extdata", "template.fasta", package = "RhodopXin")
temp <- loadSequence(temp_path)

# Find available 3d structures of given template rhodopsin
available_structs <- find3dStructure(temp)
available_structs

# Only load the first structure
rcsb_id <- available_structs$rcsb_id[1]
#loadStructure(rcsb_id)

# Print the helices segment of the template rhodopsin
findHelices(rcsb_id)
```
### Pairwise Alignment with Template
```{r}
seqs_path <- system.file("extdata", "rhodopsins.fasta", package = "RhodopXin")
seqs <- loadSequence(seqs_path) 

createPWAlignments(temp, seqs)
# Still have to format output to something nicer
```
